version: '3.3'

services:

  database:
    image: mysql:5.6
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./sklad:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sklad

  flaskapp:
    image: batareya13337/sklad_project:latest
    container_name: flaskapp
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=database  
      - DATABASE_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
volumes:
  sklad:
